import { Auth } from "aws-amplify";
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_cognito_region: "us-east-1", // (required) - Region where Amazon Cognito project was created
  aws_user_pools_id: "us-east-1_OMIU8I6eM", // (optional) -  Amazon Cognito User Pool ID
  aws_user_pools_web_client_id: "7lgk4hgqkcnson6s1qf5sthfcg", // (optional) - Amazon Cognito App Client ID (App client secret needs to be disabled)
  // aws_cognito_identity_pool_id: "us-east-1:f602c14b-0fde-409c-9a7e-0baccbfd87d0", // (optional) - Amazon Cognito Identity Pool ID
  // aws_mandatory_sign_in: "enable" // (optional) - Users are not allowed to get the aws credentials unless they are signed in

  API: {
    endpoints: [
      {
        name: "StarWarsAPI",
        endpoint: "https://3qpqryfhya.execute-api.us-east-1.amazonaws.com/Prod",
        region: "us-east-1",
        custom_header: async () => {
          return {
            Authorization: `Bearer ${(await Auth.currentSession())
              .getIdToken()
              .getJwtToken()}`,
          };
        },
      },
    ],
  },
};

export default awsmobile;
