AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ParameterUserPoolArn:
    Type: String
Resources:
  BestStarWarsPersonsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: pk
        AttributeType: S
      - AttributeName: sk
        AttributeType: S
      KeySchema:
      - AttributeName: pk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  BestStarWarsPersonsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''*'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
      Auth:
        DefaultAuthorizer: ApiCognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          ApiCognitoAuthorizer:
            UserPoolArn:
              Fn::Sub: ${ParameterUserPoolArn}
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://test-task-best-star-wars-persons/a4787e6a1e6405ef19bb373fb6719944
      Handler: lambda.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: BestStarWarsPersonsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: BestStarWarsPersonsTable
      Events:
        AddPerson:
          Type: Api
          Properties:
            RestApiId:
              Ref: BestStarWarsPersonsAPI
            Path: /users
            Method: POST
        GetPerson:
          Type: Api
          Properties:
            RestApiId:
              Ref: BestStarWarsPersonsAPI
            Path: /users
            Method: GET
        UpdatePerson:
          Type: Api
          Properties:
            RestApiId:
              Ref: BestStarWarsPersonsAPI
            Path: /users/{id}
            Method: ANY
